# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-26 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emailffa', '0005_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='emailffa.Department'),
            preserve_default=False,
        ),
    ]
