# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 06:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emailffa', '0006_job_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='department',
            new_name='tag',
        ),
    ]
