# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-31 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailffa', '0007_auto_20170728_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tag',
        ),
        migrations.AddField(
            model_name='job',
            name='tag',
            field=models.ManyToManyField(to='emailffa.Tag'),
        ),
    ]
