# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsdb', '0003_connection_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='password',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
