# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-29 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsdb', '0004_auto_20170829_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='port',
            field=models.CharField(max_length=200),
        ),
    ]
